"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { Heart } from "lucide-react";
import { Card } from "@/components/ui/card";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Button } from "@/components/ui/button";
import { toast } from "react-toastify";

export default function Donate() {
  const [donationType, setDonationType] = useState("one-time");
  const router = useRouter();
  const [amount, setAmount] = useState(5000);
  const [customAmount, setCustomAmount] = useState("");
  const [donorName, setDonorName] = useState("");
  const [donorEmail, setDonorEmail] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [isAnonymous, setIsAnonymous] = useState(false);
  const [recentDonations, setRecentDonations] = useState<any[]>([]);

  const presetAmounts = [1000, 5000, 10000, 25000, 50000];

  useEffect(() => {
    const fetchRecentDonations = async () => {
      try {
        const res = await fetch("/api/donations");
        const data = await res.json();
        if (Array.isArray(data)) setRecentDonations(data);
      } catch (e) {
        console.error("Failed to fetch donations", e);
      }
    };
    fetchRecentDonations();
  }, []);

  const handleDonate = async () => {
    if (!donorName || !donorEmail) {
      toast.error("Please fill in your name and email");
      return;
    }

    const finalAmount = customAmount ? parseInt(customAmount) : amount;

    if (!finalAmount || finalAmount < 100) {
      toast.error("Please enter a valid amount (minimum ₦100)");
      return;
    }

    setIsProcessing(true);

    try {
      // 1. Initialize payment on the server
      const initResponse = await fetch("/api/payments/initialize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          amount: finalAmount,
          email: donorEmail,
          donorName,
          donationType,
          isAnonymous,
        }),
      });

      const initData = await initResponse.json();

      if (!initData.success) {
        throw new Error(initData.error || "Failed to initialize payment");
      }

      // 2. Open Paystack Checkout using the access code from server
      if (!(window as any).PaystackPop) {
        toast.error("Payment system failed to load. Please refresh.");
        setIsProcessing(false);
        return;
      }

      const handler = (window as any).PaystackPop.setup({
        key: process.env.NEXT_PUBLIC_PAYSTACK_KEY,
        email: donorEmail,
        amount: finalAmount * 100,
        reference: initData.reference, // Use the reference generated by our server
        metadata: {
          custom_fields: [
            {
              display_name: "Donor Name",
              variable_name: "donor_name",
              value: donorName,
            },
            {
              display_name: "Donation Type",
              variable_name: "donation_type",
              value: donationType,
            },
          ],
        },
        callback: function (response: any) {
          router.push(`/donate/success?reference=${response.reference}`);
        },
        onClose: function () {
          setIsProcessing(false);
          toast.info("Transaction cancelled");
        },
      });

      handler.openIframe();
    } catch (error: any) {
      console.error("Donation error:", error);
      toast.error(error.message || "An error occurred during donation");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="py-12 md:py-16 bg-gradient-to-br from-primary/5 to-secondary/5">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
              Make a Donation
            </h1>
            <p className="text-lg text-foreground/80">
              Your generous contribution directly supports healthcare
              initiatives in underserved communities.
            </p>
          </div>
        </div>
      </section>

      {/* Donation Form */}
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-2xl mx-auto">
            <Card className="p-8">
              {/* Donation Type */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground mb-4">
                  Donation Type
                </h2>
                <RadioGroup
                  value={donationType}
                  onValueChange={setDonationType}
                >
                  <div className="flex items-center space-x-2 mb-3">
                    <RadioGroupItem value="one-time" id="one-time" />
                    <label htmlFor="one-time" className="cursor-pointer">
                      One-time Donation
                    </label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="recurring" id="recurring" />
                    <label htmlFor="recurring" className="cursor-pointer">
                      Monthly Recurring
                    </label>
                  </div>
                </RadioGroup>
              </div>

              {/* Amount Selection */}
              <div className="mb-8">
                <h2 className="text-xl font-semibold text-foreground mb-4">
                  Select Amount
                </h2>
                <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-4">
                  {presetAmounts.map((preset) => (
                    <button
                      key={preset}
                      onClick={() => {
                        setAmount(preset);
                        setCustomAmount("");
                      }}
                      className={`p-3 rounded-lg border-2 font-semibold transition-colors ${
                        amount === preset && !customAmount
                          ? "border-primary bg-primary/10 text-primary"
                          : "border-border hover:border-primary"
                      }`}
                    >
                      ₦{(preset / 1000).toFixed(0)}K
                    </button>
                  ))}
                </div>

                {/* Custom Amount */}
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Custom Amount
                  </label>
                  <div className="flex gap-2">
                    <span className="flex items-center px-3 bg-muted text-foreground/60">
                      ₦
                    </span>
                    <input
                      type="number"
                      value={customAmount}
                      onChange={(e) => {
                        setCustomAmount(e.target.value);
                        if (e.target.value) setAmount(0);
                      }}
                      placeholder="Enter custom amount"
                      className="flex-1 px-4 py-2 rounded-lg border border-border bg-background text-foreground placeholder:text-foreground/50"
                    />
                  </div>
                </div>
              </div>

              {/* Donor Info */}
              <div className="mb-8 space-y-4">
                <h2 className="text-xl font-semibold text-foreground">
                  Donor Information
                </h2>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Full Name
                  </label>
                  <input
                    type="text"
                    value={donorName}
                    onChange={(e) => setDonorName(e.target.value)}
                    placeholder="Your name"
                    className="w-full px-4 py-2 rounded-lg border border-border bg-background text-foreground placeholder:text-foreground/50"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-2">
                    Email Address
                  </label>
                  <input
                    type="email"
                    value={donorEmail}
                    onChange={(e) => setDonorEmail(e.target.value)}
                    placeholder="your@email.com"
                    className="w-full px-4 py-2 rounded-lg border border-border bg-background text-foreground placeholder:text-foreground/50"
                  />
                </div>
                <div className="flex items-center space-x-2 pt-2">
                  <input
                    type="checkbox"
                    id="anonymous"
                    checked={isAnonymous}
                    onChange={(e) => setIsAnonymous(e.target.checked)}
                    className="w-4 h-4 rounded border-border text-primary focus:ring-primary"
                  />
                  <label
                    htmlFor="anonymous"
                    className="text-sm font-medium text-foreground/70 cursor-pointer"
                  >
                    Donate anonymously
                  </label>
                </div>
              </div>

              {/* Donate Button */}
              <Button
                onClick={handleDonate}
                size="lg"
                className="w-full bg-primary hover:bg-primary/90 text-primary-foreground"
                disabled={isProcessing}
              >
                <Heart className="mr-2 h-5 w-5" />
                {isProcessing
                  ? "Processing..."
                  : `Donate ₦${(customAmount || amount).toLocaleString()}`}
              </Button>

              <p className="text-xs text-foreground/60 text-center mt-4">
                Your donation is secure and processed through our trusted
                payment partners.
              </p>
            </Card>

            {/* Recent Donations List */}
            <div className="mt-20">
              <div className="flex items-center justify-between mb-8">
                <h2 className="text-3xl font-bold text-foreground tracking-tight">
                  Community Impact
                </h2>
                <div className="h-px flex-1 mx-6 bg-gradient-to-r from-primary/30 to-transparent" />
                <span className="text-[10px] font-black text-foreground/40 uppercase tracking-[0.2em] bg-muted/50 px-4 py-1.5 rounded-full border border-border/50">
                  Live Feed
                </span>
              </div>

              <div className="grid gap-5">
                {recentDonations.length > 0 ? (
                  recentDonations.map((d, i) => (
                    <Card
                      key={i}
                      className="group p-6 bg-background/40 backdrop-blur-md border-border/40 hover:border-primary/40 hover:bg-primary/[0.02] transition-all duration-500 rounded-[2rem] shadow-sm hover:shadow-xl hover:shadow-primary/5"
                    >
                      <div className="flex justify-between items-center sm:flex-row flex-col gap-4">
                        <div className="flex items-center gap-5 w-full sm:w-auto">
                          <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center text-primary group-hover:bg-primary group-hover:text-white transition-all duration-500 shadow-inner">
                            <Heart className="w-6 h-6 fill-current group-hover:animate-pulse" />
                          </div>
                          <div>
                            <div className="flex items-center gap-2.5">
                              <p className="font-black text-foreground text-xl tracking-tight">
                                {d.donorName === "Anonymous" ? (
                                  <span className="text-foreground/30 italic font-medium">
                                    Anonymous Donor
                                  </span>
                                ) : (
                                  d.donorName
                                )}
                              </p>
                              <div
                                className={`w-2 h-2 rounded-full ${d.donorName === "Anonymous" ? "bg-foreground/10" : "bg-primary animate-pulse"}`}
                              />
                            </div>
                            <p className="text-xs text-foreground/40 font-bold uppercase tracking-widest mt-0.5">
                              {new Date(d.createdAt).toLocaleDateString(
                                undefined,
                                {
                                  month: "short",
                                  day: "numeric",
                                  year: "numeric",
                                },
                              )}{" "}
                              •{" "}
                              {new Date(d.createdAt).toLocaleTimeString([], {
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                            </p>
                          </div>
                        </div>
                        <div className="text-right w-full sm:w-auto border-t sm:border-t-0 pt-4 sm:pt-0 border-border/40">
                          <p className="text-3xl font-black text-primary tracking-tighter tabular-nums">
                            ₦{d.amount.toLocaleString()}
                          </p>
                          <p className="text-[10px] font-black text-foreground/20 uppercase tracking-[0.2em] mt-1">
                            {d.donationType || "One-time Grant"}
                          </p>
                        </div>
                      </div>
                    </Card>
                  ))
                ) : (
                  <div className="text-center py-20 bg-muted/10 rounded-[3rem] border-2 border-dashed border-border/40">
                    <Heart className="w-12 h-12 text-foreground/10 mx-auto mb-4" />
                    <p className="text-foreground/30 font-bold uppercase tracking-widest text-sm">
                      Be the first to spark a change
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
